### PR TITLE
Update DESeq2.html

### PR DESCRIPTION
**Pull request by mikelove**
oops, last time i only edited the Rmd, which didnt effect the link on the website

### CODE REVIEW

**Comment by mikelove** [comment]
Hi Joey,  Could you merge this PR when you get a chance?

**Comment by joey711** [comment]
Yes, absolutely. I'll try to get to it today. Sorry, Mike!

joey

**Comment by mikelove** [comment]
no worries :-)

**Comment by mikelove** [comment]
reminder :)

**Comment by joey711** [comment]
Done! Realized I can just merge via the github web button O:-)

Was the Rmd also updated? That will ensure future batch-rebuilds will also propagate the new link...

**Comment by mikelove** [comment]
ah, yeah the merge button makes it easy. I was curious why you said "i'll get back to it when i have time" :-) 

the other pull request fixes the Rmd:

https://github.com/joey711/phyloseq-extensions/pull/2

**Pull request merged**
